loop_on_disconnect 1

storage "/mnt/mmc" "SD1" "rw"
storage "/mnt/sdcard" "SD2" "rw"

manufacturer "muOS"
product "Device"
serial "Serial"
firmware_version "Version"
interface "MTP"

usb_vendor_id 0x1D6B
usb_product_id 0x0100
usb_class 0x6
usb_subclass 0x1
usb_protocol 0x1
usb_dev_version 0x3008

usb_functionfs_mode 0x1
usb_dev_path "/dev/usb-ffs/mtp/ep0"
usb_epin_path "/dev/usb-ffs/mtp/ep1"
usb_epout_path "/dev/usb-ffs/mtp/ep2"
usb_epint_path "/dev/usb-ffs/mtp/ep3"
usb_max_packet_size 0x200
