#!/bin/sh

# DEVICE CONFIG - AUDIO
DC_SND_CONTROL=$(PARSE_INI "$DEVICE_CONFIG" "audio" "control")
DC_SND_CHANNEL=$(PARSE_INI "$DEVICE_CONFIG" "audio" "channel")
DC_SND_MIN=$(PARSE_INI "$DEVICE_CONFIG" "audio" "min")
DC_SND_MAX=$(PARSE_INI "$DEVICE_CONFIG" "audio" "max")

export DC_SND_CONTROL
export DC_SND_CHANNEL
export DC_SND_MIN
export DC_SND_MAX
