#!/bin/sh

# DEVICE CONFIG - BATTERY
DC_BAT_CAPACITY=$(PARSE_INI "$DEVICE_CONFIG" "battery" "capacity")
DC_BAT_HEALTH=$(PARSE_INI "$DEVICE_CONFIG" "battery" "health")
DC_BAT_VOLTAGE=$(PARSE_INI "$DEVICE_CONFIG" "battery" "voltage")
DC_BAT_CHARGER=$(PARSE_INI "$DEVICE_CONFIG" "battery" "charger")

export DC_BAT_CAPACITY
export DC_BAT_HEALTH
export DC_BAT_VOLTAGE
export DC_BAT_CHARGER
