#!/bin/sh

# DEVICE CONFIG - DEVICE
DC_DEV_NAME=$(PARSE_INI "$DEVICE_CONFIG" "device" "name")
DC_DEV_HOME=$(PARSE_INI "$DEVICE_CONFIG" "device" "home")
DC_DEV_NETWORK=$(PARSE_INI "$DEVICE_CONFIG" "device" "network")
DC_DEV_BLUETOOTH=$(PARSE_INI "$DEVICE_CONFIG" "device" "bluetooth")
DC_DEV_PORTMASTER=$(PARSE_INI "$DEVICE_CONFIG" "device" "portmaster")
DC_DEV_LID=$(PARSE_INI "$DEVICE_CONFIG" "device" "lid")
DC_DEV_HDMI=$(PARSE_INI "$DEVICE_CONFIG" "device" "hdmi")
DC_DEV_EVENT=$(PARSE_INI "$DEVICE_CONFIG" "device" "event")
DC_DEV_DEBUGFS=$(PARSE_INI "$DEVICE_CONFIG" "device" "debugfs")
DC_DEV_RTC=$(PARSE_INI "$DEVICE_CONFIG" "device" "rtc")
DC_DEV_LED=$(PARSE_INI "$DEVICE_CONFIG" "device" "led")

export DC_DEV_NAME
export DC_DEV_HOME
export DC_DEV_NETWORK
export DC_DEV_BLUETOOTH
export DC_DEV_PORTMASTER
export DC_DEV_LID
export DC_DEV_HDMI
export DC_DEV_EVENT
export DC_DEV_DEBUGFS
export DC_DEV_RTC
export DC_DEV_LED
