#!/bin/sh

# DEVICE CONFIG - FIRMWARE - BOOT
DC_FIR_BOOT_OUT=$(PARSE_INI "$DEVICE_CONFIG" "firmware.boot" "out")
DC_FIR_BOOT_SEEK=$(PARSE_INI "$DEVICE_CONFIG" "firmware.boot" "seek")

# DEVICE CONFIG - FIRMWARE - PACKAGE
DC_FIR_PACKAGE_OUT=$(PARSE_INI "$DEVICE_CONFIG" "firmware.package" "out")
DC_FIR_PACKAGE_SEEK=$(PARSE_INI "$DEVICE_CONFIG" "firmware.package" "seek")

export DC_FIR_BOOT_OUT
export DC_FIR_BOOT_SEEK

export DC_FIR_PACKAGE_OUT
export DC_FIR_PACKAGE_SEEK
