#!/bin/sh

# DEVICE CONFIG - MUX
DC_MUX_WIDTH=$(PARSE_INI "$DEVICE_CONFIG" "mux" "width")
DC_MUX_HEIGHT=$(PARSE_INI "$DEVICE_CONFIG" "mux" "height")
DC_MUX_ITEM_COUNT=$(PARSE_INI "$DEVICE_CONFIG" "mux" "item_count")
DC_MUX_ITEM_HEIGHT=$(PARSE_INI "$DEVICE_CONFIG" "mux" "item_height")
DC_MUX_ITEM_PANEL=$(PARSE_INI "$DEVICE_CONFIG" "mux" "item_panel")
DC_MUX_ITEM_PREV_LOW=$(PARSE_INI "$DEVICE_CONFIG" "mux" "item_prev_low")
DC_MUX_ITEM_PREV_HIGH=$(PARSE_INI "$DEVICE_CONFIG" "mux" "item_prev_high")
DC_MUX_ITEM_NEXT_LOW=$(PARSE_INI "$DEVICE_CONFIG" "mux" "item_next_low")
DC_MUX_ITEM_NEXT_HIGH=$(PARSE_INI "$DEVICE_CONFIG" "mux" "item_next_high")

export DC_MUX_WIDTH
export DC_MUX_HEIGHT
export DC_MUX_ITEM_COUNT
export DC_MUX_ITEM_HEIGHT
export DC_MUX_ITEM_PANEL
export DC_MUX_ITEM_PREV_LOW
export DC_MUX_ITEM_PREV_HIGH
export DC_MUX_ITEM_NEXT_LOW
export DC_MUX_ITEM_NEXT_HIGH
