#!/bin/sh

# DEVICE CONFIG - NETWORK
DC_NET_MODULE=$(PARSE_INI "$DEVICE_CONFIG" "network" "module")
DC_NET_NAME=$(PARSE_INI "$DEVICE_CONFIG" "network" "name")
DC_NET_TYPE=$(PARSE_INI "$DEVICE_CONFIG" "network" "type")
DC_NET_INTERFACE=$(PARSE_INI "$DEVICE_CONFIG" "network" "iface")

export DC_NET_MODULE
export DC_NET_NAME
export DC_NET_TYPE
export DC_NET_INTERFACE
