#!/bin/sh

# DEVICE CONFIG - SDL
DC_SDL_SCALER=$(PARSE_INI "$DEVICE_CONFIG" "sdl" "scaler")
DC_SDL_ROTATION=$(PARSE_INI "$DEVICE_CONFIG" "sdl" "rotation")
DC_SDL_BLITTER_DISABLED=$(PARSE_INI "$DEVICE_CONFIG" "sdl" "blitter_disabled")

export DC_SDL_SCALER
export DC_SDL_ROTATION
export DC_SDL_BLITTER_DISABLED
