#!/bin/sh

# DEVICE CONFIG - STORAGE - BOOT
DC_STO_BOOT_DEV=$(PARSE_INI "$DEVICE_CONFIG" "storage.boot" "dev")
DC_STO_BOOT_NUM=$(PARSE_INI "$DEVICE_CONFIG" "storage.boot" "num")
DC_STO_BOOT_MOUNT=$(PARSE_INI "$DEVICE_CONFIG" "storage.boot" "mount")
DC_STO_BOOT_TYPE=$(PARSE_INI "$DEVICE_CONFIG" "storage.boot" "type")

# DEVICE CONFIG - STORAGE - ROM
DC_STO_ROM_DEV=$(PARSE_INI "$DEVICE_CONFIG" "storage.rom" "dev")
DC_STO_ROM_NUM=$(PARSE_INI "$DEVICE_CONFIG" "storage.rom" "num")
DC_STO_ROM_MOUNT=$(PARSE_INI "$DEVICE_CONFIG" "storage.rom" "mount")
DC_STO_ROM_TYPE=$(PARSE_INI "$DEVICE_CONFIG" "storage.rom" "type")

# DEVICE CONFIG - STORAGE - ROOT
DC_STO_ROOT_DEV=$(PARSE_INI "$DEVICE_CONFIG" "storage.root" "dev")
DC_STO_ROOT_NUM=$(PARSE_INI "$DEVICE_CONFIG" "storage.root" "num")
DC_STO_ROOT_MOUNT=$(PARSE_INI "$DEVICE_CONFIG" "storage.root" "mount")
DC_STO_ROOT_TYPE=$(PARSE_INI "$DEVICE_CONFIG" "storage.root" "type")

# DEVICE CONFIG - STORAGE - SDCARD
DC_STO_SDCARD_DEV=$(PARSE_INI "$DEVICE_CONFIG" "storage.sdcard" "dev")
DC_STO_SDCARD_NUM=$(PARSE_INI "$DEVICE_CONFIG" "storage.sdcard" "num")
DC_STO_SDCARD_MOUNT=$(PARSE_INI "$DEVICE_CONFIG" "storage.sdcard" "mount")
DC_STO_SDCARD_TYPE=$(PARSE_INI "$DEVICE_CONFIG" "storage.sdcard" "type")

# DEVICE CONFIG - STORAGE - USB
DC_STO_USB_DEV=$(PARSE_INI "$DEVICE_CONFIG" "storage.usb" "dev")
DC_STO_USB_NUM=$(PARSE_INI "$DEVICE_CONFIG" "storage.usb" "num")
DC_STO_USB_MOUNT=$(PARSE_INI "$DEVICE_CONFIG" "storage.usb" "mount")
DC_STO_USB_TYPE=$(PARSE_INI "$DEVICE_CONFIG" "storage.usb" "type")

export DC_STO_BOOT_DEV
export DC_STO_BOOT_NUM
export DC_STO_BOOT_MOUNT
export DC_STO_BOOT_TYPE

export DC_STO_ROM_DEV
export DC_STO_ROM_NUM
export DC_STO_ROM_MOUNT
export DC_STO_ROM_TYPE

export DC_STO_ROOT_DEV
export DC_STO_ROOT_NUM
export DC_STO_ROOT_MOUNT
export DC_STO_ROOT_TYPE

export DC_STO_SDCARD_DEV
export DC_STO_SDCARD_NUM
export DC_STO_SDCARD_MOUNT
export DC_STO_SDCARD_TYPE

export DC_STO_USB_DEV
export DC_STO_USB_NUM
export DC_STO_USB_MOUNT
export DC_STO_USB_TYPE
