wireplumber.settings = {
  monitor.alsa.reserve-device = disabled
  clock.rate                  = 44100
  clock.allowed-rates         = [ 32000, 44100, 48000 ]
  clock.quantum               = 256
  clock.min-quantum           = 256
  clock.max-quantum           = 2048
  clock.force-quantum         = 0
  clock.force-rate            = 0
  stream.restore-props        = false
}

wireplumber.profiles = {
  main = {
    support.reserve-device      = disabled
    monitor.alsa.reserve-device = disabled
  }
}

monitor.alsa.properties = {
  alsa.reserve         = false
  alsa.midi            = true
  alsa.midi.monitoring = true
}

monitor.alsa.rules = [
  {
    matches = [ { device.name = "~alsa_card.*" } ]
    actions = {
      update-props = {
        api.alsa.use-acp     = true
        api.acp.auto-profile = false
        api.acp.auto-port    = false
      }
    }
  }
  {
    matches = [ { media.class = "Audio/Sink" } ]
    actions = {
      update-props = {
        node.pause-on-idle              = false
        node.always-process             = true
        session.suspend-timeout-seconds = 0
        priority.driver                 = 2000
        priority.session                = 2000
        api.alsa.period-size            = 256
        api.alsa.periods                = 3
        api.alsa.headroom               = 128
        api.alsa.disable-batch          = true
      }
    }
  }
  {
    matches = [ { node.name = "~alsa_output.*dp0.*" } ]
    actions = {
      update-props = {
        node.pause-on-idle              = true
        session.suspend-timeout-seconds = 5
        priority.driver                 = 500
        priority.session                = 500
      }
    }
  }
  {
    matches = [ { node.name = "~alsa_output.*es8388.*" } ]
    actions = {
      update-props = {
        audio.format                    = "S24_LE"
        audio.rate                      = 44100
        node.pause-on-idle              = false
        session.suspend-timeout-seconds = 0
        priority.driver                 = 3000
        priority.session                = 3000
      }
    }
  }
  {
    matches = [ { node.name = "~alsa_output.*hdmi.*" } ]
    actions = {
      update-props = {
        priority.driver  = 2000
        priority.session = 2000
      }
    }
  }
]
