name=Clear View
description=Slightly larger text in an easy to read typeface, with a stronger highlight on the selected item
type=accessibility
settings/font/scale=115
settings/advanced/font=2
settings/font/name=Atkinson Hyperlegible
visual/boldfocus=1
visual/shadow=1
