name=Fewer Distractions
description=A quieter, calmer interface with background music, the start up chime, video and moving text turned off
type=accessibility
visual/reducemotion=1
settings/general/bgm=0
settings/general/chime=0
visual/video_wallpaper=0
visual/videopreview=0
visual/namescroll=0
visual/labelscrollspeed=1
visual/notifytime=2
