#!/bin/sh

PID_FILE="/run/haveged.pid"

case "$1" in
	start)
		if [ -f "$PID_FILE" ] && kill -0 "$(cat "$PID_FILE")" 2>/dev/null; then
			echo "Already running"
			exit 0
		fi

		printf "Starting haveged: "
		/usr/sbin/haveged -- -w 1024 -r 0 -t 4 &

		PID=$!
		echo $PID >"$PID_FILE"

		if [ -f "$PID_FILE" ]; then
			echo "OK"
		else
			echo "FAIL"
		fi
		;;
	stop)
		if [ -f "$PID_FILE" ]; then
			printf "Stopping haveged: "
			PID=$(cat "$PID_FILE")

			if kill -0 "$PID" 2>/dev/null; then
				kill "$PID"

				STATUS=$?

				rm -f "$PID_FILE"

				if [ $STATUS -eq 0 ]; then
					echo "OK"
				else
					echo "FAIL"
				fi
			else
				rm -f "$PID_FILE"
				echo "Not running"
			fi
		else
			echo "No PID file"
		fi
		;;
	restart | reload)
		stop
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart|reload}"
		exit 1
		;;
esac

exit 0
