#!/bin/sh
# shellcheck source=/dev/null

. /opt/muos/script/var/func.sh

INIT_DIR="/opt/muos/script/init"

RUN_INIT_DIR_BOUNDED stop "$INIT_DIR/async" reverse
RUN_INIT_DIR stop "$INIT_DIR" reverse

exit 0
