#!/bin/sh
# shellcheck source=/dev/null

. /opt/muos/script/var/func.sh

INIT_DIR="/opt/muos/script/init"

RUN_SCRIPT() {
	SCRIPT="$1"

	[ -e "$SCRIPT" ] || return 0
	[ -f "$SCRIPT" ] || return 0

	case "$SCRIPT" in
		*.sh)
			(
				trap - INT QUIT TSTP
				set start
				. "$SCRIPT"
			)
			;;
		*)
			"$SCRIPT" start
			;;
	esac
}

RUN_NORMAL() {
	DIR="$1"

	[ -d "$DIR" ] || return 0

	for SCRIPT in "$DIR"/S??*; do
		[ -e "$SCRIPT" ] || continue
		RUN_SCRIPT "$SCRIPT"
	done
}

RUN_ASYNC() {
	DIR="$1"

	[ -d "$DIR" ] || return 0

	for SCRIPT in "$DIR"/S??*; do
		[ -e "$SCRIPT" ] || continue
		(RUN_SCRIPT "$SCRIPT") >/dev/null 2>&1 &
	done
}

case "${1:-start}" in
	start | "")
		FBCON_DISABLE
		RUN_ASYNC "$INIT_DIR/async"
		RUN_NORMAL "$INIT_DIR"
		;;
esac

exit 0
