#!/bin/sh

# GLOBAL CONFIG - CLOCK
: "${GC_CLK_NOTATION:=0}"
: "${GC_CLK_POOL:=0}"

GC_CLK_NOTATION=$(PARSE_INI "$GLOBAL_CONFIG" "clock" "notation")
GC_CLK_POOL=$(PARSE_INI "$GLOBAL_CONFIG" "clock" "pool")

export GC_CLK_NOTATION
export GC_CLK_POOL
