#!/bin/sh

# GLOBAL CONFIG - WEB SERVICES
: "${GC_WEB_SHELL:=1}"
: "${GC_WEB_BROWSER:=0}"
: "${GC_WEB_TERMINAL:=0}"
: "${GC_WEB_SYNCTHING:=0}"
: "${GC_WEB_NTP:=1}"

GC_WEB_SHELL=$(PARSE_INI "$GLOBAL_CONFIG" "web" "shell")
GC_WEB_BROWSER=$(PARSE_INI "$GLOBAL_CONFIG" "web" "browser")
GC_WEB_TERMINAL=$(PARSE_INI "$GLOBAL_CONFIG" "web" "terminal")
GC_WEB_SYNCTHING=$(PARSE_INI "$GLOBAL_CONFIG" "web" "syncthing")
GC_WEB_NTP=$(PARSE_INI "$GLOBAL_CONFIG" "web" "ntp")

export GC_WEB_SHELL
export GC_WEB_BROWSER
export GC_WEB_TERMINAL
export GC_WEB_SYNCTHING
export GC_WEB_NTP
