#!/bin/sh

. /opt/muos/script/var/func.sh

FORCE_COPY=0
[ "$1" = "FORCE_COPY" ] && FORCE_COPY=1

DRASTIC_INPUT_SCHEMA=2
DRASTIC_MAP=$(GET_VAR "device" "board/sdl_map")
[ -n "$DRASTIC_MAP" ] || exit 1
DRASTIC_INPUT_MARKER="$DRASTIC_INPUT_SCHEMA:${DRASTIC_MAP%%,*}"

DRASTIC_BUTTON_CODE() {
	DRASTIC_BUTTON_FIELD=${DRASTIC_MAP#*,"$1":b}
	if [ "$DRASTIC_BUTTON_FIELD" = "$DRASTIC_MAP" ]; then
		printf "65535"
		return
	fi

	DRASTIC_BUTTON_INDEX=${DRASTIC_BUTTON_FIELD%%,*}
	case "$DRASTIC_BUTTON_INDEX" in
		"" | *[!0-9]*) printf "65535" ;;
		*) printf "%s" "$((1024 + DRASTIC_BUTTON_INDEX))" ;;
	esac
}

DRASTIC_A=$(DRASTIC_BUTTON_CODE a)
DRASTIC_B=$(DRASTIC_BUTTON_CODE b)
DRASTIC_X=$(DRASTIC_BUTTON_CODE x)
DRASTIC_Y=$(DRASTIC_BUTTON_CODE y)
DRASTIC_L1=$(DRASTIC_BUTTON_CODE leftshoulder)
DRASTIC_R1=$(DRASTIC_BUTTON_CODE rightshoulder)
DRASTIC_L2=$(DRASTIC_BUTTON_CODE lefttrigger)
DRASTIC_R2=$(DRASTIC_BUTTON_CODE righttrigger)
DRASTIC_R3=$(DRASTIC_BUTTON_CODE rightstick)
DRASTIC_SELECT=$(DRASTIC_BUTTON_CODE back)
DRASTIC_START=$(DRASTIC_BUTTON_CODE start)
DRASTIC_MENU=$(DRASTIC_BUTTON_CODE guide)
DRASTIC_VOLUME_DOWN=$(DRASTIC_BUTTON_CODE volumedown)
DRASTIC_VOLUME_UP=$(DRASTIC_BUTTON_CODE volumeup)

DRASTIC_ADV_SPEC="A=$DRASTIC_A|B=$DRASTIC_B|X=$DRASTIC_X|Y=$DRASTIC_Y|L=$DRASTIC_L1|R=$DRASTIC_R1"
DRASTIC_ADV_SPEC="$DRASTIC_ADV_SPEC|START=$DRASTIC_START|SELECT=$DRASTIC_SELECT|SWAP_SCREENS=$DRASTIC_R2"
DRASTIC_ADV_SPEC="$DRASTIC_ADV_SPEC|FAKE_MICROPHONE=$DRASTIC_R3|UI_SELECT=$DRASTIC_A|UI_BACK=$DRASTIC_X"
DRASTIC_ADV_SPEC="$DRASTIC_ADV_SPEC|UI_EXIT=$DRASTIC_B|UI_PAGE_UP=$DRASTIC_L1|UI_PAGE_DOWN=$DRASTIC_R1"
DRASTIC_ADV_SPEC="$DRASTIC_ADV_SPEC|UI_SWITCH=$DRASTIC_Y|HOT=$DRASTIC_MENU|HOT_TOGGLE_DPAD_MOUSE=$DRASTIC_L1"
DRASTIC_ADV_SPEC="$DRASTIC_ADV_SPEC|HOT_TOGGLE_BLUR_PIXEL=$DRASTIC_B|HOT_CHANGE_THEME=$DRASTIC_Y"
DRASTIC_ADV_SPEC="$DRASTIC_ADV_SPEC|HOT_ENTER_MENU=$DRASTIC_X|HOT_TOGGLE_FAST_FORWARD=$DRASTIC_R1"
DRASTIC_ADV_SPEC="$DRASTIC_ADV_SPEC|HOT_SAVE_STATE=$DRASTIC_R2|HOT_LOAD_STATE=$DRASTIC_L2|HOT_QUIT=$DRASTIC_START"
DRASTIC_LEG_SPEC="A=$DRASTIC_A|B=$DRASTIC_B|X=$DRASTIC_X|Y=$DRASTIC_Y|SELECT=$DRASTIC_SELECT"
DRASTIC_LEG_SPEC="$DRASTIC_LEG_SPEC|MENU=$DRASTIC_MENU|UI_SELECT=$DRASTIC_A|UI_BACK=$DRASTIC_B"
DRASTIC_LEG_SPEC="$DRASTIC_LEG_SPEC|UI_EXIT=$DRASTIC_MENU|UI_PAGE_UP=$DRASTIC_VOLUME_DOWN"
DRASTIC_LEG_SPEC="$DRASTIC_LEG_SPEC|UI_PAGE_DOWN=$DRASTIC_VOLUME_UP"

MIGRATE_DRASTIC_INPUT() {
	DRASTIC_CFG=$1
	DRASTIC_MARKER=$2
	DRASTIC_SPEC=$3

	[ -f "$DRASTIC_CFG" ] || return 0
	DRASTIC_MARKER_VALUE=
	[ -r "$DRASTIC_MARKER" ] && IFS= read -r DRASTIC_MARKER_VALUE <"$DRASTIC_MARKER"
	if [ "$FORCE_COPY" -eq 0 ] && [ "$DRASTIC_MARKER_VALUE" = "$DRASTIC_INPUT_MARKER" ]; then
		return 0
	fi

	mkdir -p /tmp/mustardos
	DRASTIC_TMP=$(mktemp /tmp/mustardos/drastic.XXXXXX) || return 1
	if ! awk -v replacements="$DRASTIC_SPEC" '
		BEGIN {
			count = split(replacements, pairs, "|")
			for (i = 1; i <= count; i++) {
				split(pairs[i], pair, "=")
				value[pair[1]] = pair[2]
			}
		}
		{
			found = 0
			for (key in value) {
				prefix = "controls_b[CONTROL_INDEX_" key "]"
				if (index($0, prefix) == 1) {
					print prefix " = " value[key]
					found = 1
					break
				}
			}
			if (!found) print
		}
	' "$DRASTIC_CFG" >"$DRASTIC_TMP"; then
		rm -f "$DRASTIC_TMP"
		return 1
	fi

	if ! cmp -s "$DRASTIC_CFG" "$DRASTIC_TMP"; then
		cp -f "$DRASTIC_TMP" "$DRASTIC_CFG" || {
			rm -f "$DRASTIC_TMP"
			return 1
		}
	fi

	rm -f "$DRASTIC_TMP"
	printf "%s" "$DRASTIC_INPUT_MARKER" >"$DRASTIC_MARKER"
}

DRASTIC_ADV="$MUOS_SHARE_DIR/emulator/drastic-trngaje"
DRASTIC_ADV_JSON="${DRASTIC_ADV}/resources/settings.json"
DRASTIC_ADV_CFG="${DRASTIC_ADV}/config/drastic.cfg"

if [ "$FORCE_COPY" -eq 1 ] || [ ! -f "$DRASTIC_ADV_JSON" ]; then
	mkdir -p "${DRASTIC_ADV}/resources"
	cp -f "$DEVICE_CONTROL_DIR/drastic-trngaje/settings.json" "$DRASTIC_ADV_JSON" || exit 1
fi

if [ "$FORCE_COPY" -eq 1 ] || [ ! -f "$DRASTIC_ADV_CFG" ]; then
	mkdir -p "${DRASTIC_ADV}/config"
	cp -f "$DEVICE_CONTROL_DIR/drastic-trngaje/drastic.cfg" "$DRASTIC_ADV_CFG" || exit 1
fi
DRASTIC_RESULT=0
MIGRATE_DRASTIC_INPUT "$DRASTIC_ADV_CFG" "${DRASTIC_ADV}/config/.muos-input-schema" "$DRASTIC_ADV_SPEC" ||
	DRASTIC_RESULT=1

DRASTIC_LEG="$MUOS_SHARE_DIR/emulator/drastic-legacy"
DRASTIC_LEG_CFG="${DRASTIC_LEG}/config/drastic.cfg"

if [ "$FORCE_COPY" -eq 1 ] || [ ! -f "$DRASTIC_LEG_CFG" ]; then
	mkdir -p "${DRASTIC_LEG}/config"
	cp -f "$DEVICE_CONTROL_DIR/drastic.cfg" "$DRASTIC_LEG_CFG" || exit 1
fi
MIGRATE_DRASTIC_INPUT "$DRASTIC_LEG_CFG" "${DRASTIC_LEG}/config/.muos-input-schema" "$DRASTIC_LEG_SPEC" ||
	DRASTIC_RESULT=1

exit "$DRASTIC_RESULT"
