LABEL muos
  LINUX /boot/Image
  FDT /boot/rk3576-anbernic-rg-vita-pro.dtb
  APPEND rootwait root=/dev/mmcblk1p4 init=/linuxrc console=ttyS2,1500000n8 fbcon=rotate:3 vt.global_cursor_default=0 pcie_aspm=off coherent_pool=2M cma=64M
