7z a -tzip "Beanz.zip" ".\Beanz\*"
7z a -tzip "C64.zip" ".\C64\*"
7z a -tzip "Catppuccin Frappe.zip" ".\Catppuccin Frappe\*"
7z a -tzip "Disk Sys.zip" ".\Disk Sys\*"
7z a -tzip "Dracula.zip" ".\Dracula\*"
7z a -tzip "Faux Dark.zip" ".\Faux Dark\*"
7z a -tzip "GB Dark.zip" ".\GB Dark\*"
7z a -tzip "mubiOS.zip" ".\mubiOS\*"
7z a -tzip "muOS - Banana.zip" ".\muOS - Banana\*"
7z a -tzip "muOS - Beans.zip" ".\muOS - Beans\*"
7z a -tzip "muOS - Classic.zip" ".\muOS - Classic\*"
7z a -tzip "muVB.zip" ".\muVB\*"
7z a -tzip "Orange.zip" ".\Orange\*"
