ODROIDGO2-UBOOT-CONFIG

setenv bootargs "root=/dev/mmcblk0p2 rw rootwait quiet loglevel=0 fbcon=nodefer vt.global_cursor_default=0 init=/sbin/init"

# --- Memory Load Addresses ---
setenv loadaddr "0x02000000"
setenv dtb_loadaddr "0x1000000"

load mmc 1:1 ${loadaddr} Image

load mmc 1:1 ${dtb_loadaddr} rk3326-batlexp-linux.dtb

booti ${loadaddr} - ${dtb_loadaddr}


