#!/bin/sh

. /opt/muos/script/var/func.sh

. /opt/muos/script/var/device/input.sh

COUNT_UP=0
STATE_UP=0
PRESS_UP="*code $DC_INP_RAW_DPAD_UP * value -1*"
RELEASE_UP="*code $DC_INP_RAW_DPAD_UP * value 0*"

COUNT_DOWN=0
STATE_DOWN=0
PRESS_DOWN="*code $DC_INP_RAW_DPAD_DOWN * value 1*"
RELEASE_DOWN="*code $DC_INP_RAW_DPAD_DOWN * value 0*"

COUNT_LEFT=0
STATE_LEFT=0
PRESS_LEFT="*code $DC_INP_RAW_DPAD_LEFT * value -1*"
RELEASE_LEFT="*code $DC_INP_RAW_DPAD_LEFT * value 0*"

COUNT_RIGHT=0
STATE_RIGHT=0
PRESS_RIGHT="*code $DC_INP_RAW_DPAD_RIGHT * value 1*"
RELEASE_RIGHT="*code $DC_INP_RAW_DPAD_RIGHT * value 0*"

COUNT_A=0
STATE_A=0
PRESS_A="*code $DC_INP_RAW_BUTTON_A * value 1*"
RELEASE_A="*code $DC_INP_RAW_BUTTON_A * value 0*"

COUNT_B=0
STATE_B=0
PRESS_B="*code $DC_INP_RAW_BUTTON_B * value 1*"
RELEASE_B="*code $DC_INP_RAW_BUTTON_B * value 0*"

COUNT_C=0
STATE_C=0
PRESS_C="*code $DC_INP_RAW_BUTTON_C * value 1*"
RELEASE_C="*code $DC_INP_RAW_BUTTON_C * value 0*"

COUNT_X=0
STATE_X=0
PRESS_X="*code $DC_INP_RAW_BUTTON_X * value 1*"
RELEASE_X="*code $DC_INP_RAW_BUTTON_X * value 0*"

COUNT_Y=0
STATE_Y=0
PRESS_Y="*code $DC_INP_RAW_BUTTON_Y * value 1*"
RELEASE_Y="*code $DC_INP_RAW_BUTTON_Y * value 0*"

COUNT_Z=0
STATE_Z=0
PRESS_Z="*code $DC_INP_RAW_BUTTON_Z * value 1*"
RELEASE_Z="*code $DC_INP_RAW_BUTTON_Z * value 0*"

COUNT_SELECT=0
STATE_SELECT=0
PRESS_SELECT="*code $DC_INP_RAW_BUTTON_SELECT * value 1*"
RELEASE_SELECT="*code $DC_INP_RAW_BUTTON_SELECT * value 0*"

COUNT_START=0
STATE_START=0
PRESS_START="*code $DC_INP_RAW_BUTTON_START * value 1*"
RELEASE_START="*code $DC_INP_RAW_BUTTON_START * value 0*"

COUNT_MENU_SHORT=0
STATE_MENU_SHORT=0
PRESS_MENU_SHORT="*code $DC_INP_RAW_BUTTON_MENU_SHORT * value 1*"
RELEASE_MENU_SHORT="*code $DC_INP_RAW_BUTTON_MENU_SHORT * value 0*"

COUNT_MENU_LONG=0
STATE_MENU_LONG=0
PRESS_MENU_LONG="*code $DC_INP_RAW_BUTTON_MENU_LONG * value 1*"
RELEASE_MENU_LONG="*code $DC_INP_RAW_BUTTON_MENU_LONG * value 0*"

COUNT_L1=0
STATE_L1=0
PRESS_L1="*code $DC_INP_RAW_BUTTON_L1 * value 1*"
RELEASE_L1="*code $DC_INP_RAW_BUTTON_L1 * value 0*"

COUNT_L2=0
STATE_L2=0
PRESS_L2="*code $DC_INP_RAW_BUTTON_L2 * value 1*"
RELEASE_L2="*code $DC_INP_RAW_BUTTON_L2 * value 0*"

COUNT_L3=0
STATE_L3=0
PRESS_L3="*code $DC_INP_RAW_BUTTON_L3 * value 1*"
RELEASE_L3="*code $DC_INP_RAW_BUTTON_L3 * value 0*"

COUNT_R1=0
STATE_R1=0
PRESS_R1="*code $DC_INP_RAW_BUTTON_R1 * value 1*"
RELEASE_R1="*code $DC_INP_RAW_BUTTON_R1 * value 0*"

COUNT_R2=0
STATE_R2=0
PRESS_R2="*code $DC_INP_RAW_BUTTON_R2 * value 1*"
RELEASE_R2="*code $DC_INP_RAW_BUTTON_R2 * value 0*"

COUNT_R3=0
STATE_R3=0
PRESS_R3="*code $DC_INP_RAW_BUTTON_R3 * value 1*"
RELEASE_R3="*code $DC_INP_RAW_BUTTON_R3 * value 0*"

COUNT_VOL_UP=0
STATE_VOL_UP=0
PRESS_VOL_UP="*code $DC_INP_RAW_BUTTON_VOL_UP * value 1*"
RELEASE_VOL_UP="*code $DC_INP_RAW_BUTTON_VOL_UP * value 0*"

COUNT_VOL_DOWN=0
STATE_VOL_DOWN=0
PRESS_VOL_DOWN="*code $DC_INP_RAW_BUTTON_VOL_DOWN * value 1*"
RELEASE_VOL_DOWN="*code $DC_INP_RAW_BUTTON_VOL_DOWN * value 0*"

COUNT_POWER_SHORT=0
STATE_POWER_SHORT=0
PRESS_POWER_SHORT="*code $DC_INP_RAW_BUTTON_POWER_SHORT * value 1*"
RELEASE_POWER_SHORT="*code $DC_INP_RAW_BUTTON_POWER_SHORT * value 0*"

COUNT_POWER_LONG=0
STATE_POWER_LONG=0
PRESS_POWER_LONG="*code $DC_INP_RAW_BUTTON_POWER_LONG * value 2*"
RELEASE_POWER_LONG="*code $DC_INP_RAW_BUTTON_POWER_LONG * value 0*"
